<%
out.println("<!DOCTYPE HTML>");
out.println("<html lang=\"en\">");
out.println("<html>");
out.println("");
out.println("");
out.println("<head>");
out.println("		<title> NOTEPAD </title>");
out.println("		");
out.println("		<meta charset=\"UTF-8\" />");
out.println("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />");
out.println("</head>");
out.println("");
out.println("<body style=\"background-color:gray;\">");
out.println("");
out.println("");
out.println("");
out.println("  <table collapsed id = 'testTable' >");
out.println("	<tr>");
out.println("		<td >**Ticket Number  :**</td>");
out.println("		<td><input type=\"Tnumber\" style=\"background-color:lightgray;\" id=\"Tnumber\" >");
out.println("		");
out.println("		</td>");
out.println("		  ");
out.println("		");
out.println("		");
out.println("		");
out.println("		");
out.println("    </tr>");
out.println("	");
out.println("	<tr>");
out.println("		<td>**Phone # :**</td>");
out.println("		<td><input type=\"phone\" style=\"background-color:lightgray;\" id=\"phone\"></td>");
out.println("	</tr>");
out.println("	 <tr>");
out.println("		<td>**Domain Name :**</td>");
out.println("		<td><input type=\"Dname\" style=\"background-color:lightgray;\" id=\"Dname\"></td>");
out.println("	</tr>");
out.println("   ");
out.println("	<tr>");
out.println("		<td>**Full Name :**</td>");
out.println("		<td><input type=\"Fname\" style=\"background-color:lightgray; \" id=\"Fname\"></td>");
out.println("	</tr>");
out.println("   ");
out.println("	<tr>");
out.println("		<td>**Account Number :**</td>");
out.println("		<td><input type=\"Anumber\" style=\"background-color:lightgray;\" id=\"Anumber\"></td>");
out.println("	</tr>");
out.println("	<tr>");
out.println("		<td>**Email :**</td>");
out.println("		<td><input type=\"Email\" style=\"background-color:lightgray;\" id=\"Email\"></td>");
out.println("	</tr>");
out.println("   ");
out.println("    ");
out.println("   ");
out.println("  ");
out.println("   ");
out.println("   <tr>");
out.println("		<td>**CX Authenticated ? :**</td>");
out.println("		<td>");
out.println("		<select name=\"AUTH\" id=\"auth\" style=\"background-color:lightgray;\">");
out.println("			<option value=\"Clear\" ></option>");
out.println("			<option value=\"Yes\">YES</option>");
out.println("			<option value=\"No\"> NO</option>");
out.println("		</select> :");
out.println("		<select name=\"Amethod\" id=\"authMethod\" style=\"background-color:lightgray;\">");
out.println("			<option value=\"clear\" ></option>");
out.println("			<option value=\"N/A\"> N/A</option>");
out.println("			<option value=\"PIN\"> PIN</option>");
out.println("			<option value=\"SQ\">SQ</option>");
out.println("			<option value=\"2FA\">2FA</option>");
out.println("			");
out.println("			");
out.println("		</select>");
out.println("		");
out.println("		</td>");
out.println("	 ");
out.println("   </tr>");
out.println("   <tr>");
out.println("   ");
out.println("    <td><label for=\"Issue\" >**Issue :**</label></td>");
out.println("");
out.println("		<td><select name=\"Issue\" id=\"issue\" style=\"background-color:lightgray;\">");
out.println("			<option value=\"Clear\" ></option>");
out.println("			<option value=\"GeneralQ\">General Questions</option>");
out.println("			<option value=\"AAccess\">Account Access</option>");
out.println("			<option value=\"PER/PCR\"> Password Reset</option>");
out.println("			<option value=\"Renewal \">Renewal</option>");
out.println("			<option value=\"Refund \"> Chargeback Reversal  </option>");
out.println("			<option value=\"PER/PCR\"> PER/PCR</option>");
out.println("			<option value=\"RNCA\"> RNCA</option>");
out.println("			<option value=\"DNS\">DNS/DNS Edit</option>");
out.println("			<option value=\"Refund\">Refund</option>");
out.println("			<option value=\"Billing\">Billing</option>");
out.println("			<option value=\"DomainTrasferIn\">Domain Transfer In</option>");
out.println("			<option value=\"Billing\">Domain Transfer Out</option>");
out.println("			<option value=\"Email\">Email</option>");
out.println("			<option value=\"Hosting\">Hosting</option>");
out.println("			<option value=\"WDown\">Website Down</option>");
out.println("			<option value=\"WModification\">Website Modification</option>");
out.println("			<option value=\"IVerification\">ICANN Verification </option>");
out.println("			<option value=\"DLocks\">Domain Locks</option>");
out.println("			<option value=\"SSL\">SSL Certificate/Installation </option>");
out.println("			");
out.println("		</select></td>");
out.println("   </tr>");
out.println("   ");
out.println("   <td>**Additional Notes  :**</td>");
out.println("    <td><textarea id=\"Anotes\" name=\"Anotes\" rows=\"22\" cols=\"30\" style=\"background-color:lightgray;\">");
out.println("	</textarea></td>");
out.println("	 ");
out.println(" <td> <br> </td>");
out.println("	  <tr>");
out.println("   ");
out.println("    <td><label for=\"Cresult\">**Case Result  :**</label></td>");
out.println("");
out.println("		<td><select name=\"Creason\" id=\"cars\" style=\"background-color:lightgray;\">");
out.println("			<option value=\"Clear\"></option>");
out.println("			<option value=\"Transfer\">Transferred</option>");
out.println("			<option value=\"Escalated\">Escalated</option>");
out.println("			<option value=\"Close \">Closed</option>");
out.println("		");
out.println("			");
out.println("			");
out.println("		</select></td>");
out.println("		</tr>");
out.println("	");
out.println("   ");
out.println("");
out.println("  ");
out.println("");
out.println("  </table>");
out.println("  ");
out.println("  ");
out.println("   ");
out.println("   ");
out.println("   ");
out.println("  ");
out.println("  <button id = \"button\"  ><img src=\"pngegg.png\"  width=\"20\" height=\"20\"></button>");
out.println("");
out.println("   <button onClick=\"window.location.reload();\" ><img src=\"clear.jpg\"  width=\"20\" height=\"20\"></button></br>");
out.println("	  ");
out.println("  ");
out.println("   ");
out.println("");
out.println(" 	");
out.println("");
out.println("");
out.println("");
out.println("");
out.println("<script>");
out.println("let table = document.querySelector('#testTable');");
out.println("let button = document.querySelector('#button');");
out.println("");
out.println("function selectNode(node){");
out.println("  let range  =  document.createRange();");
out.println("  range.selectNodeContents(node)");
out.println("  let select =  window.getSelection()");
out.println("  select.removeAllRanges()");
out.println("  select.addRange(range)");
out.println("}");
out.println("button.addEventListener('click',function(){");
out.println("  selectNode(table);");
out.println("  document.execCommand('copy');");
out.println("  alert(\"Notes Copied !\" );");
out.println("  ");
out.println("})");
out.println("");
out.println("");
out.println("</script>");
out.println("");
out.println("");
out.println(" <span class=\"time\" id=\"display\">00:00:00</span>");
out.println("      </div>");
out.println("");
out.println("      <div class=\"controls\">");
out.println("        <button class=\"buttonPlay\">");
out.println("          <img id=\"playButton\" src=\"https://res.cloudinary.com/https-tinloof-com/image/upload/v1593360448/blog/time-in-js/play-button_opkxmt.svg\" height= \"20\" width=\"20\" />");
out.println("");
out.println("          <img id=\"pauseButton\" src=\"https://res.cloudinary.com/https-tinloof-com/image/upload/v1593360448/blog/time-in-js/pause-button_pinhpy.svg\" height= \"20\" width=\"20\" />");
out.println("        </button>");
out.println("");
out.println("        <button class=\"buttonReset\">");
out.println("          <img id=\"resetButton\" src=\"https://res.cloudinary.com/https-tinloof-com/image/upload/v1593360448/blog/time-in-js/reset-button_mdv6wf.svg\" height= \"18\" width=\"20\" />");
out.println("        </button>");
out.println("      </div>");
out.println("    </div>");
out.println("    <script src=\"js-timeout.js\"></script>");
out.println("");
out.println("		");
out.println("		");
out.println("		");
out.println("</body>");
out.println("</html>");
%>